apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-docker-runner.fullname" . }}
  labels: {{- include "gitlab-docker-runner.labels" . | nindent 4 }}
type: Opaque
data:
  runner-registration-token: {{ default "" .Values.runnerRegistrationToken | b64enc | quote }}
