apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zabbix-server.fullname" . }}-psk
  labels:
    {{- include "zabbix-server.labels" . | nindent 4 }}
type: Opaque
{{ include "zabbix-server.psk" . }}
